apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: blog-django-py
    app.kubernetes.io/component: blog-django-py
    app.kubernetes.io/instance: blog-django-py
    app.kubernetes.io/part-of: blog-django-py-app
  name: blog-django-py
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: blog-django-py:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    contextDir: /
    git:
      uri: https://github.com/openshift-katacoda/blog-django-py
    type: Git
  strategy:
    dockerStrategy:
      dockerfilePath: Dockerfile
    type: Docker
  successfulBuildsHistoryLimit: 5
  triggers:
  - generic:
      secretReference:
        name: blog-django-py-generic-webhook-secret
    type: Generic
  - github:
      secretReference:
        name: blog-django-py-github-webhook-secret
    type: GitHub
  - type: ConfigChange